/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Message_H
#define Message_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "tutorial_types.h"

namespace tutorial {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MessageIf {
 public:
  virtual ~MessageIf() {}
  virtual void ping() = 0;
};

class MessageIfFactory {
 public:
  typedef MessageIf Handler;

  virtual ~MessageIfFactory() {}

  virtual MessageIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MessageIf* /* handler */) = 0;
};

class MessageIfSingletonFactory : virtual public MessageIfFactory {
 public:
  MessageIfSingletonFactory(const boost::shared_ptr<MessageIf>& iface) : iface_(iface) {}
  virtual ~MessageIfSingletonFactory() {}

  virtual MessageIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MessageIf* /* handler */) {}

 protected:
  boost::shared_ptr<MessageIf> iface_;
};

class MessageNull : virtual public MessageIf {
 public:
  virtual ~MessageNull() {}
  void ping() {
    return;
  }
};


class Message_ping_args {
 public:

  Message_ping_args(const Message_ping_args&);
  Message_ping_args& operator=(const Message_ping_args&);
  Message_ping_args() {
  }

  virtual ~Message_ping_args() throw();

  bool operator == (const Message_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Message_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Message_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Message_ping_pargs {
 public:


  virtual ~Message_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Message_ping_result {
 public:

  Message_ping_result(const Message_ping_result&);
  Message_ping_result& operator=(const Message_ping_result&);
  Message_ping_result() {
  }

  virtual ~Message_ping_result() throw();

  bool operator == (const Message_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Message_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Message_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Message_ping_presult {
 public:


  virtual ~Message_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MessageClient : virtual public MessageIf {
 public:
  MessageClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MessageClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MessageProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<MessageIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MessageProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MessageProcessor(boost::shared_ptr<MessageIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &MessageProcessor::process_ping;
  }

  virtual ~MessageProcessor() {}
};

class MessageProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MessageProcessorFactory(const ::boost::shared_ptr< MessageIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MessageIfFactory > handlerFactory_;
};

class MessageMultiface : virtual public MessageIf {
 public:
  MessageMultiface(std::vector<boost::shared_ptr<MessageIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MessageMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MessageIf> > ifaces_;
  MessageMultiface() {}
  void add(boost::shared_ptr<MessageIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MessageConcurrentClient : virtual public MessageIf {
 public:
  MessageConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MessageConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
