/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Calculator_H
#define Calculator_H

#include <stdio.h>
#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "calc_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class CalculatorIf {
 public:
  virtual ~CalculatorIf() {}
  virtual int32_t add(const int32_t a, const int32_t b) = 0;
  virtual int32_t sub(const int32_t a, const int32_t b) = 0;
  virtual int32_t mult(const int32_t a, const int32_t b) = 0;
  virtual int32_t div(const int32_t a, const int32_t b) = 0;
};

class CalculatorIfFactory {
 public:
  typedef CalculatorIf Handler;

  virtual ~CalculatorIfFactory() {}

  virtual CalculatorIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(CalculatorIf* /* handler */) = 0;
};

class CalculatorIfSingletonFactory : virtual public CalculatorIfFactory {
 public:
  CalculatorIfSingletonFactory(const boost::shared_ptr<CalculatorIf>& iface) : iface_(iface) {}
  virtual ~CalculatorIfSingletonFactory() {}

  virtual CalculatorIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(CalculatorIf* /* handler */) {}

 protected:
  boost::shared_ptr<CalculatorIf> iface_;
};

class CalculatorNull : virtual public CalculatorIf {
 public:
  virtual ~CalculatorNull() {}
  int32_t add(const int32_t /* a */, const int32_t /* b */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t sub(const int32_t /* a */, const int32_t /* b */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t mult(const int32_t /* a */, const int32_t /* b */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t div(const int32_t /* a */, const int32_t /* b */) {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _Calculator_add_args__isset {
  _Calculator_add_args__isset() : a(false), b(false) {}
  bool a :1;
  bool b :1;
} _Calculator_add_args__isset;

class Calculator_add_args {
 public:

  Calculator_add_args(const Calculator_add_args&);
  Calculator_add_args& operator=(const Calculator_add_args&);
  Calculator_add_args() : a(0), b(0) {
  }

  virtual ~Calculator_add_args() throw();
  int32_t a;
  int32_t b;

  _Calculator_add_args__isset __isset;

  void __set_a(const int32_t val);

  void __set_b(const int32_t val);

  bool operator == (const Calculator_add_args & rhs) const
  {
    if (!(a == rhs.a))
      return false;
    if (!(b == rhs.b))
      return false;
    return true;
  }
  bool operator != (const Calculator_add_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_add_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_add_pargs {
 public:


  virtual ~Calculator_add_pargs() throw();
  const int32_t* a;
  const int32_t* b;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_add_result__isset {
  _Calculator_add_result__isset() : success(false) {}
  bool success :1;
} _Calculator_add_result__isset;

class Calculator_add_result {
 public:

  Calculator_add_result(const Calculator_add_result&);
  Calculator_add_result& operator=(const Calculator_add_result&);
  Calculator_add_result() : success(0) {
  }

  virtual ~Calculator_add_result() throw();
  int32_t success;

  _Calculator_add_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Calculator_add_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Calculator_add_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_add_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_add_presult__isset {
  _Calculator_add_presult__isset() : success(false) {}
  bool success :1;
} _Calculator_add_presult__isset;

class Calculator_add_presult {
 public:


  virtual ~Calculator_add_presult() throw();
  int32_t* success;

  _Calculator_add_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Calculator_sub_args__isset {
  _Calculator_sub_args__isset() : a(false), b(false) {}
  bool a :1;
  bool b :1;
} _Calculator_sub_args__isset;

class Calculator_sub_args {
 public:

  Calculator_sub_args(const Calculator_sub_args&);
  Calculator_sub_args& operator=(const Calculator_sub_args&);
  Calculator_sub_args() : a(0), b(0) {
  }

  virtual ~Calculator_sub_args() throw();
  int32_t a;
  int32_t b;

  _Calculator_sub_args__isset __isset;

  void __set_a(const int32_t val);

  void __set_b(const int32_t val);

  bool operator == (const Calculator_sub_args & rhs) const
  {
    if (!(a == rhs.a))
      return false;
    if (!(b == rhs.b))
      return false;
    return true;
  }
  bool operator != (const Calculator_sub_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_sub_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_sub_pargs {
 public:


  virtual ~Calculator_sub_pargs() throw();
  const int32_t* a;
  const int32_t* b;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_sub_result__isset {
  _Calculator_sub_result__isset() : success(false) {}
  bool success :1;
} _Calculator_sub_result__isset;

class Calculator_sub_result {
 public:

  Calculator_sub_result(const Calculator_sub_result&);
  Calculator_sub_result& operator=(const Calculator_sub_result&);
  Calculator_sub_result() : success(0) {
  }

  virtual ~Calculator_sub_result() throw();
  int32_t success;

  _Calculator_sub_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Calculator_sub_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Calculator_sub_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_sub_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_sub_presult__isset {
  _Calculator_sub_presult__isset() : success(false) {}
  bool success :1;
} _Calculator_sub_presult__isset;

class Calculator_sub_presult {
 public:


  virtual ~Calculator_sub_presult() throw();
  int32_t* success;

  _Calculator_sub_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Calculator_mult_args__isset {
  _Calculator_mult_args__isset() : a(false), b(false) {}
  bool a :1;
  bool b :1;
} _Calculator_mult_args__isset;

class Calculator_mult_args {
 public:

  Calculator_mult_args(const Calculator_mult_args&);
  Calculator_mult_args& operator=(const Calculator_mult_args&);
  Calculator_mult_args() : a(0), b(0) {
  }

  virtual ~Calculator_mult_args() throw();
  int32_t a;
  int32_t b;

  _Calculator_mult_args__isset __isset;

  void __set_a(const int32_t val);

  void __set_b(const int32_t val);

  bool operator == (const Calculator_mult_args & rhs) const
  {
    if (!(a == rhs.a))
      return false;
    if (!(b == rhs.b))
      return false;
    return true;
  }
  bool operator != (const Calculator_mult_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_mult_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_mult_pargs {
 public:


  virtual ~Calculator_mult_pargs() throw();
  const int32_t* a;
  const int32_t* b;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_mult_result__isset {
  _Calculator_mult_result__isset() : success(false) {}
  bool success :1;
} _Calculator_mult_result__isset;

class Calculator_mult_result {
 public:

  Calculator_mult_result(const Calculator_mult_result&);
  Calculator_mult_result& operator=(const Calculator_mult_result&);
  Calculator_mult_result() : success(0) {
  }

  virtual ~Calculator_mult_result() throw();
  int32_t success;

  _Calculator_mult_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Calculator_mult_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Calculator_mult_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_mult_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_mult_presult__isset {
  _Calculator_mult_presult__isset() : success(false) {}
  bool success :1;
} _Calculator_mult_presult__isset;

class Calculator_mult_presult {
 public:


  virtual ~Calculator_mult_presult() throw();
  int32_t* success;

  _Calculator_mult_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Calculator_div_args__isset {
  _Calculator_div_args__isset() : a(false), b(false) {}
  bool a :1;
  bool b :1;
} _Calculator_div_args__isset;

class Calculator_div_args {
 public:

  Calculator_div_args(const Calculator_div_args&);
  Calculator_div_args& operator=(const Calculator_div_args&);
  Calculator_div_args() : a(0), b(0) {
  }

  virtual ~Calculator_div_args() throw();
  int32_t a;
  int32_t b;

  _Calculator_div_args__isset __isset;

  void __set_a(const int32_t val);

  void __set_b(const int32_t val);

  bool operator == (const Calculator_div_args & rhs) const
  {
    if (!(a == rhs.a))
      return false;
    if (!(b == rhs.b))
      return false;
    return true;
  }
  bool operator != (const Calculator_div_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_div_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_div_pargs {
 public:


  virtual ~Calculator_div_pargs() throw();
  const int32_t* a;
  const int32_t* b;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_div_result__isset {
  _Calculator_div_result__isset() : success(false) {}
  bool success :1;
} _Calculator_div_result__isset;

class Calculator_div_result {
 public:

  Calculator_div_result(const Calculator_div_result&);
  Calculator_div_result& operator=(const Calculator_div_result&);
  Calculator_div_result() : success(0) {
  }

  virtual ~Calculator_div_result() throw();
  int32_t success;

  _Calculator_div_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Calculator_div_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Calculator_div_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_div_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_div_presult__isset {
  _Calculator_div_presult__isset() : success(false) {}
  bool success :1;
} _Calculator_div_presult__isset;

class Calculator_div_presult {
 public:


  virtual ~Calculator_div_presult() throw();
  int32_t* success;

  _Calculator_div_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class CalculatorClient : virtual public CalculatorIf {
 public:
  CalculatorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  CalculatorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t add(const int32_t a, const int32_t b);
  void send_add(const int32_t a, const int32_t b);
  int32_t recv_add();
  int32_t sub(const int32_t a, const int32_t b);
  void send_sub(const int32_t a, const int32_t b);
  int32_t recv_sub();
  int32_t mult(const int32_t a, const int32_t b);
  void send_mult(const int32_t a, const int32_t b);
  int32_t recv_mult();
  int32_t div(const int32_t a, const int32_t b);
  void send_div(const int32_t a, const int32_t b);
  int32_t recv_div();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class CalculatorProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<CalculatorIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (CalculatorProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_add(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_sub(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_mult(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_div(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  CalculatorProcessor(boost::shared_ptr<CalculatorIf> iface) :
    iface_(iface) {
    processMap_["add"] = &CalculatorProcessor::process_add;
    processMap_["sub"] = &CalculatorProcessor::process_sub;
    processMap_["mult"] = &CalculatorProcessor::process_mult;
    processMap_["div"] = &CalculatorProcessor::process_div;
  }

  virtual ~CalculatorProcessor() {}
};

class CalculatorProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  CalculatorProcessorFactory(const ::boost::shared_ptr< CalculatorIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< CalculatorIfFactory > handlerFactory_;
};

class CalculatorMultiface : virtual public CalculatorIf {
 public:
  CalculatorMultiface(std::vector<boost::shared_ptr<CalculatorIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~CalculatorMultiface() {}
 protected:
  std::vector<boost::shared_ptr<CalculatorIf> > ifaces_;
  CalculatorMultiface() {}
  void add(boost::shared_ptr<CalculatorIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t add(const int32_t a, const int32_t b) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->add(a, b);
    }
    return ifaces_[i]->add(a, b);
  }

  int32_t sub(const int32_t a, const int32_t b) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->sub(a, b);
    }
    return ifaces_[i]->sub(a, b);
  }

  int32_t mult(const int32_t a, const int32_t b) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->mult(a, b);
    }
    return ifaces_[i]->mult(a, b);
  }

  int32_t div(const int32_t a, const int32_t b) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->div(a, b);
    }
    return ifaces_[i]->div(a, b);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class CalculatorConcurrentClient : virtual public CalculatorIf {
 public:
  CalculatorConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  CalculatorConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t add(const int32_t a, const int32_t b);
  int32_t send_add(const int32_t a, const int32_t b);
  int32_t recv_add(const int32_t seqid);
  int32_t sub(const int32_t a, const int32_t b);
  int32_t send_sub(const int32_t a, const int32_t b);
  int32_t recv_sub(const int32_t seqid);
  int32_t mult(const int32_t a, const int32_t b);
  int32_t send_mult(const int32_t a, const int32_t b);
  int32_t recv_mult(const int32_t seqid);
  int32_t div(const int32_t a, const int32_t b);
  int32_t send_div(const int32_t a, const int32_t b);
  int32_t recv_div(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
